#!/usr/bin/env ruby
require 'turney'

if ARGV.count < 1
  puts "Please supply the number of teams"
  puts "Usage: #{__FILE__} <number>"
  exit 1
end
number_of_teams = ARGV.first.to_i
winner, brackets = Turney.start(number_of_teams)
puts "#{winner.name.capitalize} won the tournament"
